name: run publish

inputs:
  github-token:
    description: the github token
  node-auth-token:
    description: node auth token

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        registry-url: https://registry.npmjs.org/
    - uses: extractions/setup-just@v2
    - name: publish to npm
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{inputs.node-auth-token}}
      run: |
        echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
        npm install --frozen-lockfile
        npm run generate
        npm run build
        npm publish --tag latest --access=public
    - name: github release
      shell: bash
      env:
        GITHUB_TOKEN: ${{inputs.github-token}}
      run: just create-release
