name: on release
on:
  release:
    types: [published]

jobs:
  tests:
    steps:
      - uses: actions/checkout@v4
      - uses: .github/workflows/run-tests.yaml

  release:
    needs: tests
    steps:
    - uses: actions/checkout@v4
    - uses: .github/workflows/run-release.yaml
