name: on release
on:
  push:
    tags: ['*']

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test

  release:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/publish
      with:
        node-auth-token: ${{secrets.NODE_AUTH_TOKEN}}
